updated patterns and partitioning
yast/system-role-hpc-server pull request #7
Opened 2018-04-20 14:01 UTC by mslacken

- changed required pattern from minimal_base to base bsc#1090282 
- added subvolume description to installation.xml to make btrfs
  available on guided partitioner (bsc#1090380)
- changed workload_server to hpc_workload_server (bsc#108951)

2018-04-20 14:23 UTC, imobachgs requested changes

2018-04-20 14:23 UTC, imobachgs commented on control/installation.xml
> +		  <!-- using base as minimal_base would nearly provide as much packages as
The comment looks confusing to me (maybe it is just me). What I read is:  *"base" would nearly provide as much packages as "base"*.

2018-04-20 14:23 UTC, imobachgs commented on control/installation.xml
> +			<snapshots config:type="boolean">true</snapshots>
Please, check indentation

2018-04-20 17:12 UTC, mslacken commented on control/installation.xml
> +		  <!-- using base as minimal_base would nearly provide as much packages as
Should be: using base instead of mininmal_base

2018-04-20 17:13 UTC, mslacken commented on control/installation.xml
> +			<snapshots config:type="boolean">true</snapshots>
are there rules for that? vim command would also be fine.

2018-04-23 10:08 UTC, imobachgs approved these changes

2018-04-23 10:08 UTC, merged